name: MGTBench
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.3=py38h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=8.0.0=py38h60b952e_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.2=py38h06a4308_0
  - attrs=22.1.0=py38h06a4308_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - aws-c-common=0.4.57=he6710b0_1
  - aws-c-event-stream=0.1.6=h2531618_5
  - aws-checksums=0.1.9=he6710b0_0
  - aws-sdk-cpp=1.8.185=hce553d0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.5=pyhd8ed1ab_0
  - boost-cpp=1.73.0=h7f8727e_12
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2023.01.10=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.0=pyhd8ed1ab_0
  - certifi=2022.12.7=py38h06a4308_0
  - cffi=1.15.1=py38h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cryptography=38.0.4=py38h9ce1e76_0
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.0.140=0
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.0.140=0
  - cuda-nsight-compute=12.0.1=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.0.140=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.0.146=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=12.0.146=0
  - cuda-runtime=11.6.1=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.0.140=0
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-visual-tools=11.6.1=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.9=h27cfd23_1
  - filelock=3.9.0=py38h06a4308_0
  - flatbuffers=2.0.0=h2531618_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fontconfig=2.14.1=h52c9d5c_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py38h5eee18b_0
  - fsspec=2022.11.0=py38h06a4308_0
  - gast=0.4.0=pyh9f0ad1d_0
  - gds-tools=1.5.1.14=0
  - gflags=2.2.2=he6710b0_0
  - giflib=5.2.1=h5eee18b_1
  - glib=2.69.1=he621ea3_2
  - glog=0.5.0=h2531618_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.16.1=pyh1a96a4e_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpc-cpp=1.46.1=h33aed49_1
  - grpcio=1.42.0=py38hce63b2e_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=3.1.0=nompi_py38hafa665b_100
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - huggingface_hub=0.10.1=py38h06a4308_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.15.0=pyh210e3f2_0
  - ipython=8.10.0=py38h06a4308_0
  - jedi=0.18.1=py38h06a4308_1
  - joblib=1.1.1=py38h06a4308_0
  - jpeg=9e=h7f8727e_0
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_core=5.2.0=py38h578d9bd_0
  - keras=2.10.0=py38h06a4308_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py38h6a678d5_0
  - krb5=1.19.4=h568e23c_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libboost=1.73.0=h28710b8_12
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=10.0.1=default_hb85057a_2
  - libcublas=11.9.2.110=h5e84587_0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.7.1.112=hf425ae0_0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.5.1.14=0
  - libcufile-dev=1.5.1.14=0
  - libcurand=10.3.1.124=0
  - libcurand-dev=10.3.1.124=0
  - libcurl=7.87.0=h91b91d3_0
  - libcusolver=11.3.4.124=h33c3c4e_0
  - libcusparse=11.7.2.124=h7538f96_0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libnghttp2=1.46.0=hce63b2e_0
  - libnpp=11.6.3.124=hd2722f0_0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnvjpeg=11.6.2.124=hd473ad6_0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libthrift=0.15.0=hcc01f38_0
  - libtiff=4.5.0=h6a678d5_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown=3.4.1=pyhd8ed1ab_0
  - matplotlib=3.6.2=py38h06a4308_0
  - matplotlib-base=3.6.2=py38h945d387_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - multidict=6.0.2=py38h5eee18b_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - nsight-compute=2022.4.1.6=0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numexpr=2.8.4=py38he184ba9_0
  - numpy=1.23.5=py38h14f4228_0
  - numpy-base=1.23.5=py38h31eccc5_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - orc=1.7.4=hb3bc3d3_1
  - packaging=22.0=py38h06a4308_0
  - pandas=1.5.2=py38h417a72b_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.3.0=py38h6a678d5_2
  - pip=22.3.1=py38h06a4308_0
  - platformdirs=3.0.0=pyhd8ed1ab_0
  - ply=3.11=py38_0
  - prompt-toolkit=3.0.36=py38h06a4308_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=8.0.0=py38h992f0b0_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycodestyle=2.10.0=py38h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pyqt=5.15.7=py38h6a678d5_1
  - pyqt5-sip=12.11.0=py38h6a678d5_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.16=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-flatbuffers=23.1.21=pyhd8ed1ab_0
  - python-xxhash=2.0.2=py38h5eee18b_1
  - python_abi=3.8=2_cp38
  - pytorch=1.13.1=py3.8_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py38h06a4308_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py38h5eee18b_1
  - pyzmq=19.0.2=py38ha71036d_2
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - regex=2022.7.9=py38h5eee18b_0
  - requests=2.28.1=py38h06a4308_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - responses=0.13.3=pyhd3eb1b0_0
  - rsa=4.9=pyhd8ed1ab_0
  - scikit-learn=1.2.0=py38h6a678d5_1
  - scipy=1.9.3=py38h14f4228_0
  - seaborn=0.12.2=py38h06a4308_0
  - setuptools=65.6.3=py38h06a4308_0
  - sip=6.6.2=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h295c915_0
  - sqlite=3.40.1=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tensorboard=2.10.0=py38h06a4308_0
  - tensorboard-data-server=0.6.1=py38h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.10.0=mkl_py38hd2379f1_0
  - tensorflow-base=2.10.0=mkl_py38hb9daa73_0
  - tensorflow-estimator=2.10.0=py38h06a4308_0
  - tensorflow-hub=0.12.0=pyhca92ed8_0
  - termcolor=2.2.0=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - tokenizers=0.11.4=py38h3dcd8bd_1
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.13.1=py38_cu116
  - torchvision=0.14.1=py38_cu116
  - tornado=6.2=py38h5eee18b_0
  - tqdm=4.64.1=py38h06a4308_0
  - traitlets=5.7.1=py38h06a4308_0
  - transformers=4.24.0=py38h06a4308_0
  - typing-extensions=4.4.0=py38h06a4308_0
  - typing_extensions=4.4.0=py38h06a4308_0
  - urllib3=1.26.14=py38h06a4308_0
  - utf8proc=2.6.1=h27cfd23_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=2.1.2=pyhd8ed1ab_1
  - wheel=0.38.4=py38h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.8.1=py38h5eee18b_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - anytree==2.8.0
    - beautifulsoup4==4.11.2
    - bert-score==0.3.13
    - bpemb==0.3.4
    - click==8.0.4
    - cloudpickle==2.2.1
    - conllu==4.5.2
    - data==0.4
    - datasets==2.4.0
    - deprecated==1.2.13
    - dill==0.3.5.1
    - docopt==0.6.2
    - editdistance==0.6.2
    - flair==0.11.3
    - fst-pso==1.8.1
    - ftfy==6.1.1
    - funcsigs==1.0.2
    - future==0.18.3
    - fuzzytm==2.0.5
    - gdown==4.4.0
    - gensim==4.3.0
    - hyperopt==0.2.7
    - importlib-metadata==3.10.1
    - janome==0.4.2
    - jieba==0.42.1
    - konoha==4.6.5
    - langdetect==1.0.9
    - language-tool-python==2.7.1
    - latex==0.7.0
    - lemminflect==0.2.3
    - lru-dict==1.1.8
    - lxml==4.9.2
    - miniful==0.0.6
    - more-itertools==9.1.0
    - mpld3==0.3
    - multiprocess==0.70.13
    - networkx==3.0
    - nltk==3.8.1
    - num2words==0.5.12
    - openai==0.26.5
    - openhownet==2.0
    - overrides==3.1.0
    - pinyin==0.4.0
    - pptree==3.1
    - protobuf==4.22.0
    - py4j==0.10.9.7
    - pycld2==0.41
    - pyfume==0.2.25
    - segtok==1.5.11
    - sentencepiece==0.1.95
    - shutilwhich==1.1.0
    - simpful==2.10.0
    - smart-open==6.3.0
    - soupsieve==2.4
    - sqlitedict==2.1.0
    - tabulate==0.9.0
    - tempdir==0.7.1
    - terminaltables==3.1.10
    - textattack==0.3.8
    - wikipedia-api==0.5.8
    - word2number==1.1
    - wrapt==1.15.0
prefix: /home/allen/anaconda3/envs/MGTBench
